### ISSUE TITLE
文件接收不正常

### ISSUE THREAD

**Issue by tsztodd** [Chocolatl/qqlight-websocket#1]
使用示例进行测试，发送了一个文件，收到一个语音。。。
另外，能否开发一个HTTP(S)协议的插件

**Comment by chocolatl** [comment]
@tsztodd 事件是由QQLight框架提供的，该插件只做了转发的工作，发送文件收到语音的问题可以向框架作者反馈

另外并没有做HTTP协议插件的打算，因为HTTP不能比WebSocket更好的完成双向通信的工作
