### ISSUE TITLE
加群请求经常不成功

### ISSUE THREAD

**Issue by yearsx** [Chocolatl/qqlight-websocket#10]
大佬，邀请加群和主动加群经常不成功是什么情况啊？
另外接口getLoginAccount能否同时返回登录QQ号码和昵称？
接口 退出群能否增加一个是否永久拒绝此人入群参数？
事件 收到消息时能否同时把对方的昵称、群名片、群角色同步返回呢？

**Comment by chocolatl** [comment]
> 邀请加群和主动加群经常不成功是什么情况啊？

加群不成功应该是QQ机器人那边的问题，和插件无关

> 另外接口getLoginAccount能否同时返回登录QQ号码和昵称？

插件提供的都是底层接口，与易语言/C++等的SDK基本一致，这个需求应该自己封装

> 接口 退出群能否增加一个是否永久拒绝此人入群参数？

没弄懂什么意思

> 事件 收到消息时能否同时把对方的昵称、群名片、群角色同步返回呢？

插件提供的都是底层接口，与易语言/C++等的SDK基本一致，这个需求应该自己封装

**Comment by yearsx** [comment]
> 大佬，邀请加群和主动加群经常不成功是什么情况啊？
> 另外接口getLoginAccount能否同时返回登录QQ号码和昵称？
> 接口 退出群能否增加一个是否永久拒绝此人入群参数？
> 事件 收到消息时能否同时把对方的昵称、群名片、群角色同步返回呢？
