### ISSUE TITLE
请教一下 api.h 中函数指针全局变量的问题

### ISSUE THREAD

**Issue by pandolia** [Chocolatl/qqlight-websocket#11]
首先感谢作者提供了如此简单和优美的 websocket 接口。关于源码中有个问题想请教一下您，在 api.h 中定义的函数指针全局变量，比如下面这个：

    const char* __stdcall (*QL_getPluginPath)(const char* authCode);

这里定义了一个指针类型的全局变量。但这个 api.h 又被好几个源文件 include ，按我的理解，似乎是应该只有一个源文件中是定义变量，其他源文件中都只是声明变量，需要加上 extern 关键字，比如：

    extern const char* __stdcall (*QL_getPluginPath)(const char* authCode);

这里为什么可以不加修改的被多个源文件 include ，且可以正常链接而不报重复定义的错？

**Comment by chocolatl** [comment]
你说的对，正确的做法是在头文件中使用`extern`声明变量，我的写法是错误的。

至于为什么可以工作，估计是编译器做了额外的工作：
<https://stackoverflow.com/questions/1433204/how-do-i-use-extern-to-share-variables-between-source-files>#Not so good way to define global variables

**Comment by pandolia** [comment]
谢谢您的解答！
