### ISSUE TITLE
你好👋，它似乎不能接收到加好友请求了？

### ISSUE THREAD

**Issue by fumeboy** [Chocolatl/qqlight-websocket#15]
向机器人发起加好友请求后，QQlight 的日志里会有这个记录，说明QQlight 是成功接收到信息的，然而 插件这边，服务器并没有发送任何信息过来

**Comment by fumeboy** [comment]
![image](https://user-images.githubusercontent.com/30453942/58398877-f96ba600-8088-11e9-81f8-509e7b6701ff.png)
在 main.c 我发现了……
657行，AddFrinend 你拼写错了单词

**Comment by chocolatl** [comment]
单词不是我拼错的，是QQLight作者拼错的，我只好将错就错了

**Comment by chocolatl** [comment]
看了一下，应该是作者在新版的QQLight修正了拼写错误的问题，然后没有做向后兼容导致的

**Comment by fumeboy** [comment]
……可是这样我这边也不能拿到数据，你自己测试的话是可行的吗

OK

**Comment by chocolatl** [comment]
已修复，谢谢你的反馈
