### ISSUE TITLE
调用获取群列表

### ISSUE THREAD

**Issue by markstien** [Chocolatl/qqlight-websocket#16]
![捕获](https://user-images.githubusercontent.com/26346161/61768591-80839300-ae1a-11e9-801e-6cea3de31297.PNG)

这个地方也要有id，不然会报错。
但是文档没有写。

**Comment by chocolatl** [comment]
所有方法都要添加ID字段的：<https://github.com/Chocolatl/qqlight-websocket#%E6%8E%A5%E5%8F%A3>
