### ISSUE TITLE
如何发起临时会话？

### ISSUE THREAD

**Issue by markstien** [Chocolatl/qqlight-websocket#17]
如题，请大佬指点一下

**Comment by chocolatl** [comment]
<https://github.com/Chocolatl/qqlight-websocket#%E6%8E%A5%E5%8F%A3%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF>

**Comment by markstien** [comment]
> https://github.com/Chocolatl/qqlight-websocket#%E6%8E%A5%E5%8F%A3%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF
如果和机器人不是好友也可以发送消息吗？

`{
        id:`123`,
        method:"sendMessage",
        params:{
            type:6,
            group:"",
            qq:`2721911317`,
            content:"hama"
        }`
这样好像发送不出去。。。

**Comment by chocolatl** [comment]
估计至少需要是在同一个群，而且可能还有其它限制。如果确定这个功能失效可以找QQLight作者反馈。

另外id字段是string而不是number
