### ISSUE TITLE
QQLight3.0出正式版了，2.x版本插件不能用了，麻烦作者更新一下

### ISSUE THREAD

**Issue by Ax0ne** [Chocolatl/qqlight-websocket#19]
3.0地址：https://www.52chat.cc/forum.php?mod=viewthread&tid=410

**Comment by chocolatl** [comment]
已经升级到3.0版本插件，新接口以后有时间再加了，凑合着先用吧

**Comment by Ax0ne** [comment]
> 已经升级到3.0版本插件，新接口以后有时间再加了，凑合着先用吧

好的，新接口用不上，能兼容旧插件就行了。辛苦。
