### ISSUE TITLE
版本v2.0.1 事件.收到好友请求 事件.成为好友 无法触发

### ISSUE THREAD

**Issue by nlysh007** [Chocolatl/qqlight-websocket#20]
版本v2.0.1 事件.收到好友请求 事件.成为好友 无法触发

**Comment by chocolatl** [comment]
已添加新的事件替换原有事件：<https://github.com/Chocolatl/qqlight-websocket#%E4%BA%8B%E4%BB%B6%E5%A5%BD%E5%8F%8B%E5%8F%98%E5%8A%A8>
请更新一下插件

**Comment by nlysh007** [comment]
事件.好友变动 测试已经可用了，事件.收到好友请求（friendRequest）似乎是我没开好友验证的原因
