### ISSUE TITLE
QL最近几次的升级太操蛋了，我愿意捐赠移植一个契约版的socket插件

### ISSUE THREAD

**Issue by Ax0ne** [Chocolatl/qqlight-websocket#22]
麻烦作者有时间弄一个契约版的socket插件，可以留下微信或支付宝大家好方便捐赠。
契约QQ下载地址：https://qyue.cc/topic/165

**Comment by chocolatl** [comment]
抱歉，
现在不玩QQ机器人了，而且现在很忙。所以没有继续开发插件的打算
