### ISSUE TITLE
qqlight-websocket做为客户端

### ISSUE THREAD

**Issue by ourlog** [Chocolatl/qqlight-websocket#23]
能出一个qqlight-websocket作为客户端的版本么。
遇到这么一个场景：需要一个集中处理QQ消息服务器，消息服务器还要挂接其他的业务服务器。是一个被动型的处理，不是向QQ主动发送消息

因为水平问题，不知道怎么把处理QQ消息的ws客户端集成在web服务器上，如果qqlight-websocket是ws的客户端，那么就能在自己的服务器上业务处理。不用再写一个中间的qq消息处理了。

**Comment by chocolatl** [comment]
没听懂。

**Comment by ourlog** [comment]
我的意思是说，qqlight-websocket做为 websocket的客户端，不做服务端。启动的时候插件去连接用户的websocket服务器

**Comment by chocolatl** [comment]
这个你自己写一个客户端做中转就行了。

**Comment by ourlog** [comment]
现在就是在做中转客户端
