### ISSUE TITLE
使用python socketio client连接400错误

### ISSUE THREAD

**Issue by ourlog** [Chocolatl/qqlight-websocket#24]
使用python socketio client连接qqlight-ws报400错误，但是python连接flask_websocketio服务器没问题。
在网页上用js可以连接qqlight-ws确是好的。

**Comment by chocolatl** [comment]
麻烦贴一下连接失败时QQLight上的日志

**Comment by ourlog** [comment]
exec(code, run_globals)
  File "/home/test/dev_work/qqagent/listenqq.py", line 21, in <module>
    sio.connect('ws://172.20.2.41:49632/')
  File "/home/test/miniconda3/lib/python3.7/site-packages/socketio/client.py", line 270, in connect
    six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
  File "<string>", line 3, in raise_from
socketio.exceptions.ConnectionError: Unexpected status code 400 in server response

**Comment by ourlog** [comment]
同样的python代码连接我用flask_websocketio做的服务器是可以的

**Comment by ourlog** [comment]
日志：
12-17 23:28:35  WebSocket Protocol  receiveConnect    Accepted client: 64.7.0.0:60525
12-17 23:28:35  WebSocket Protocol  wsShakeHands    Unexpected request line
12-17 23:28:35  WebSocket Protocol  removeClient    Client socket closed, now length of clients: 0

**Comment by chocolatl** [comment]
[websocket.protocol.ql.dll.zip](https://github.com/Chocolatl/qqlight-websocket/files/3974105/websocket.protocol.ql.dll.zip)

麻烦用这个再发一遍日志

**Comment by ourlog** [comment]
12-17 23:44:27  WebSocket Protocol  receiveConnect    Accepted client: 64.7.0.0:60525
12-17 23:44:27  WebSocket Protocol  wsShakeHands    Unexpected request line
12-17 23:44:27  WebSocket Protocol  removeClient    Client socket closed, now length of clients: 0

就只有这三行

**Comment by ourlog** [comment]
qqlight是3.1.9版

**Comment by chocolatl** [comment]
删除plugin/temp目录再刷新插件试试，如果还是没有我也不清楚为什么了。

**Comment by ourlog** [comment]
发错了，换了插件后的日志是：
12-17 23:55:05  WebSocket Protocol  receiveConnect    Accepted client: 244.6.0.0:0
12-17 23:55:05  WebSocket Protocol  wsShakeHands    Unexpected request line
12-17 23:55:05  WebSocket Protocol  wsShakeHands    GET / HTTP/1.1
12-17 23:55:05  WebSocket Protocol  removeClient    Client socket closed, now length of clients: 0

**Comment by chocolatl** [comment]
[websocket.protocol.ql.dll.zip](https://github.com/Chocolatl/qqlight-websocket/files/3974244/websocket.protocol.ql.dll.zip)

不好意思，打错日志了。。

用这个再发一遍

**Comment by ourlog** [comment]
12-18 00:09:41  WebSocket Protocol  receiveConnect    Accepted client: 104.6.0.0:0
12-18 00:09:41  WebSocket Protocol  wsShakeHands    Unexpected request line
12-18 00:09:41  WebSocket Protocol  wsShakeHands    GET /socket.io/?transport=polling&EIO=3&t=1576598981.8055713 HTTP/1.1
Host: 172.20.2.41:49632
User-Agent: python-requests/2.22.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive

12-18 00:09:41  WebSocket Protocol  removeClient    Client socket closed, now length of clients: 0

来了

**Comment by chocolatl** [comment]
看了一下 这个库看起来不是解决通用websocket场景的，而是对标js的socket.io设计的。所以还是使用其它库吧

**Comment by chocolatl** [comment]
你可以试试这样写有没有用
```
sio.connect('http://localhost:49632', namespaces=['/'])
```

**Comment by ourlog** [comment]
好的，我换个别的库看看

**Comment by ourlog** [comment]
果然如此，换成websocket-client这个库，可以了：
12-18 00:37:22  WebSocket Protocol  receiveConnect    Accepted client: 104.6.0.0:60525
12-18 00:37:22  WebSocket Protocol  wsShakeHands    WebSocket handshake succeeded
