### ISSUE TITLE
监听地址问题

### ISSUE THREAD

**Issue by aaron-yang-biz** [Chocolatl/qqlight-websocket#4]
监听地址为localhost，而非0.0.0.0。
最新的源代码似乎已变更为0.0.0.0，但发行版插件似乎仍然使用了localhost地址，见下图：

**Comment by aaron-yang-biz** [comment]
无法贴图：

Active Connections

  Proto  Local Address          Foreign Address        State
  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING
  TCP    127.0.0.1:49632        0.0.0.0:0              LISTENING
  TCP    192.168.1.8:139        0.0.0.0:0              LISTENING

**Comment by chocolatl** [comment]
@suitool 请确认下载的是0.4.1而不是0.4.0，我这边测试已经可以通过外网访问

**Comment by aaron-yang-biz** [comment]
是我之前下载的dll，忘了更新。谢谢！

**Comment by aaron-yang-biz** [comment]
中秋快乐！

**Comment by chocolatl** [comment]
中秋快乐
