### ISSUE TITLE
python client connect issue

### ISSUE THREAD

**Issue by aaron-yang-biz** [Chocolatl/qqlight-websocket#5]
得到以下错误：
（插件日志）
09-24 16:07:44  WebSocket Protocol  receiveComingData    Bytes received: 179
09-24 16:07:44  WebSocket Protocol  wsShakeHands    Missing required fields

客户端日志：
ERROR:root:HTTP 400: Bad Request
Traceback (most recent call last):
  File "C:/workspace/qqlight/client.py", line 26, in connect
    self.ws = yield websocket_connect(self.url)
  File "C:\Users\yangy\Miniconda3\envs\qqlight\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
tornado.httpclient.HTTPClientError: HTTP 400: Bad Request

客户端代码：

class Client(object):
    def __init__(self, url, timeout):
        self.url = url
        self.timeout = timeout
        self.ioloop = IOLoop.instance()
        self.ws = None
        self.connect()
        self.ioloop.start()

    @gen.coroutine
    def connect(self):
        try:
            self.ws = yield websocket_connect(self.url)
        except Exception as e:
            logger.exception(e)
        else:
            logger.info("connected")
            self.run()

if __name__ == "__main__":
    client = Client("ws://192.168.1.8:49632/", 5)
这段代码连接别的客户端是没问题的。
另基于js的客户端代码示例也没有问题，可以连接

**Comment by aaron-yang-biz** [comment]
上述代码使用了tornado库。如果使用另一个库websockets 6.0，则可以连接。应该是对 协议升级部分的兼容性问题

**Comment by chocolatl** [comment]
我会重写一下接受握手请求的部分

**Comment by aaron-yang-biz** [comment]
好，辛苦！

**Comment by chocolatl** [comment]
@suitool 试试现在在tornado中能否正常握手，如果依然不能，请把日志发给我

[websocket.protocol.plugin.dll.zip](https://github.com/Chocolatl/qqlight-websocket/files/2410745/websocket.protocol.plugin.dll.zip)

**Comment by aaron-yang-biz** [comment]
好，有几天没看这个issue(改用websockets6.0了）。这两天有时间再看。辛苦！

**Comment by aaron-yang-biz** [comment]
已改用websockets 6.0了，很稳定！
