### ISSUE TITLE
addFriend: invalid data issue

### ISSUE THREAD

**Issue by aaron-yang-biz** [Chocolatl/qqlight-websocket#6]
09-24 19:52:03  WebSocket Protocol  wsClientDataHandle    Payload data is {"method": "addFriend", "params": {"qq": 1927115659, "message": "test add friend"}}

09-24 19:49:59  WebSocket Protocol  wsClientDataHandle    Payload data is {"method": "addFriend", "params": {"qq": "1927115659", "message": "test add friend"}}

09-24 19:52:03  WebSocket Protocol  jsonRPC    Client call 'addFriend' method
09-24 19:52:03  WebSocket Protocol  jsonParse    Invalid data

无论是哪种调用格式都是合格的json，为何认定数据格式无效？

**Comment by aaron-yang-biz** [comment]
原因找到了，不是bug，是需要增加id字段，即：

`
{
  "id": "xxxx-xx-xxx-xxx",
  "params": {
      "qq":  "1927115659",
      "message": "test add friend"
   }
}
`

**Comment by chocolatl** [comment]
其实是BUG，无返回值的方法不需要添加`id`
