### ISSUE TITLE
文档支持

### ISSUE THREAD

**Issue by aaron-yang-biz** [Chocolatl/qqlight-websocket#9]
缺少以下文档：
1. 一些API请求中，对数据类型的格式没有说明。比如请求字段/返回结果字段应该是字符串还是数字等。
2. 没有错误码说明：比如我遇到下面的问题：
recv {"id":"622d1364-b848-4d9c-942d-d728b458b8b0","result":{"ec":4,"em":"basekey&nbsp;err"}}
这是请求
10-19 20:10:17  WebSocket Protocol  wsClientDataHandle    Payload data is {"method": "getGroupList", "id": "622d1364-b848-4d9c-942d-d728b458b8b0"}
的返回结果。从qqlight日志上看，请求是成功了的。

**Comment by aaron-yang-biz** [comment]
版本是最新的，插件没有版本号，我这边看大小是110592字节

**Comment by chocolatl** [comment]
请求格式和字段数据类型文档是有标注的，返回字段格式与数据类型调用一次查看结果就知道了

返回结果和框架API返回结果是保持一致的，所以获取群列表错误的问题可以向QQLight作者反馈

**Comment by aaron-yang-biz** [comment]
谢谢解答！

**Comment by aaron-yang-biz** [comment]
谢谢解答！
